behaviors:
  Racing:
    trainer_type: ppo
    max_steps: 5.0e6
    time_horizon: 128
    keep_checkpoints: 5
    summary_freq: 50000
    threaded: false
    hyperparameters:
      beta: 0.01
      epsilon: 0.2
      lambd: 0.97
      num_epoch: 3
      batch_size: 64
      buffer_size: 1024
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
      gail:
        strength: 0.01
        gamma: 0.99
        encoding_size: 128
        demo_path: D:\Autonomous Racing\demos\Racing.demo
    behavioral_cloning:
      demo_path: D:\Autonomous Racing\demos\Racing.demo
      strength: 0.5
      steps: 0
